### ISSUE TITLE
Implement a histogram feature

### ISSUE THREAD

**Issue by amilcarlucas** [ros-visualization/rqt_plot#43]
It would be nice if you could merge the histogram feature from https://github.com/krystiancha/rqt_histogram

of course without removing 2D plot support and without renaming the package

**Comment by dirk-thomas** [comment]
I am not sure I understand: you want the plot plugin to show the 2d plot as well as the histogram? Why not keep these two seemingly independent visualizations in separate plugins?

Anyway please consider to contribute a pull request with the idea. (Though it might be good to first clarify the exact behavior afterwards to avoid doing work which then doesn't get merged.)

**Comment by amilcarlucas** [comment]
The repo I mentioned renamed the rqt_plot plugin into rqt_histogram and keeps independent visualizations. That is fine. but what I wanted is for both 2d_plot and histograms to be available from the same repo, avoiding code duplication.

I do not know however what is the best way to change your code to support both options while minimizing code duplication. And exacly there is where I would like your help and opinion.

**Comment by dirk-thomas** [comment]
> I wanted is for both 2d_plot and histograms to be available from the same repo

Why? I don't see any reason for that.

> avoiding code duplication

A package can already use the API provided by other packages by simply depending on them. No need to be in the same repo for that.

> minimizing code duplication. And exacly there is where I would like your help and opinion.

I would suggest opening an issue in the `rqt_histogram` repo and suggesting to consolidate the duplicated code by reusing the API provided by `rqt_plot`. If there is a need to refactor the code in this repo to expose more functionality in a reusable API please consider creating pull requests to achieve that - I am more than happy to review them.

If this answers your question please go ahead and close this ticket since there doesn't seem to be anything which needs to be done in this repo.

**Comment by amilcarlucas** [comment]
OK, I guess I need to take a look at the API.
